dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
#  - "3.9-dev" # replace once pylint issue is fixed
# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
# command to run tests
script:
  - make install travis_safe_tests